services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=twitter-clone'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'  # Use fixed port mapping
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Add volume for persistence

volumes:
  postgres_data:  # Define the volume