name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service] # Add new services here as you create them
        # Example: service: [user-service, post-service, auth-service]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build ${{ matrix.service }} with Maven
      run: mvn -B package --file ${{ matrix.service }}/pom.xml
      
    #- name: Run tests for ${{ matrix.service }}
    #  run: mvn -B test --file ${{ matrix.service }}/pom.xml

  dependency-submission:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        service: [user-service] # Make sure this matches the list in the build job
        # Example: service: [user-service, post-service, auth-service]
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Update dependency graph for ${{ matrix.service }}
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        directory: ${{ matrix.service }}
